### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by wwj154** [mengshukeji/LuckysheetServer#2]
项目启动的时候为啥要连接到mongodb数据库

**Comment by fansq-j** [comment]
这个要改成mongodb的吧，不过现在没改而已，程序了也留了选用数据库的场景

**Comment by runningBolin** [comment]
同问，能否先将mongodb的配置加上。现在加上MongoDB的连接配置以后也是错误的，不能正常启动。

**Comment by iamxuchen800117** [comment]
在WebApplication启动类中将
@SpringBootApplication(scanBasePackages = "com.xc"})
替换为如下代码
@SpringBootApplication(scanBasePackages = "com.xc",exclude={MongoAutoConfiguration.class})

**Comment by dream-num** [comment]
check mysql tutorial: [Use MySQL Tutorial for Beginners](https://github.com/mengshukeji/LuckysheetServer/wiki/Use-MySQL-Tutorial-for-Beginners)
