### ISSUE TITLE
server启动后会报mongodb连接失败的异常，麻烦提交下mongodb相关的配置，万分感谢~

### ISSUE THREAD

**Issue by runningBolin** [mengshukeji/LuckysheetServer#3]
server启动后会报mongodb连接失败的异常，如图：
![image](https://user-images.githubusercontent.com/20654595/101747322-9a547180-3b06-11eb-92ba-8b9690d51f22.png)

请先提交下mongodb相关的配置项，感谢~

**Comment by MrStupidBird** [comment]
项目没有用到mongodb（只是用到了spring-data-mongodb包提供的一些类），直接把mongodb的启动配置删了就可以

**Comment by runningBolin** [comment]
@MrStupidBird 项目中并没有看到有mongodb相关的启动配置

**Comment by iamxuchen800117** [comment]
在WebApplication启动类中将
@SpringBootApplication(scanBasePackages = "com.xc"})
替换为如下代码
@SpringBootApplication(scanBasePackages = "com.xc",exclude={MongoAutoConfiguration.class})

**Comment by runningBolin** [comment]
@iamxuchen800117 感谢回复已解决
