### ISSUE TITLE
[BUG]发现了个bug

### ISSUE THREAD

**Issue by andrew7baker** [mengshukeji/LuckysheetServer#9]
**描述错误**
`{ status: "0", msg: "Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: url not set", data: "{}", code: "SYS0" }`

**重现**
重现错误的步骤：
1.本地启动LuckysheetServer,数据库客户端正常访问，application-dev.yml修改正确
2.http://127.0.0.1:9004/luckysheet/test/dbInit 报
`{
status: "0",
msg: "Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: url not set",
data: "{}",
code: "SYS0"
}`
   

**期望的结果**
http://127.0.0.1:9004/luckysheet/test/dbInit
能正常返回。

**屏幕截图或演示**
方便的话，贴上屏幕截图或在线链接复现问题，我们复测时会更精准
![image](https://user-images.githubusercontent.com/50053092/104914356-fb0a8000-59c9-11eb-8e1c-74080b679afe.png)

![image](https://user-images.githubusercontent.com/50053092/104828822-2432ef80-58a8-11eb-9e61-ff2b9e3ee371.png)

**环境：**
  -操作系统：[Windows，Linux]
  -浏览器 版本号：[例如 Chrome 版本 87.0.4147.105（正式版本） （64 位）]
  -Luckysheet版本：[最新]

**备注**
其他说明

**Comment by iamxuchen800117** [comment]
提供下，配置截图

**Comment by andrew7baker** [comment]
logging:
  config: classpath:logback-spring.xml

# 日志是否打印sql
showSql: true


spring:
  redis:
    host: vb-home
    port: 6379
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0

db:
  postgre:
    druid:
      url: jdbc:postgresql://vb-home:5432/luckysheetdb?useSSL=false
      driverClassName: org.postgresql.Driver
      username: postgres
      password: 123456
      # 初始化大小，最小，最大
      initial-size: 8
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-timeMillis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

**Comment by andrew7baker** [comment]
`# 配置server参数
server:
  port: 9004
  servlet:
    context-path: /luckysheet
spring:
  profiles:
    active: @profiles.active@`

上面这一行是不是写错了？

**Comment by wjt123125** [comment]
请教一下，这个怎么解决？

**Comment by wjt123125** [comment]
我遇到了相同的问题
